### ISSUE TITLE
Normal for the scan task to stop at Phase 1 ?

### ISSUE THREAD

**Issue by AkikoOrenji** [pentagridsec/PentagridScanController#7]
For me it seems like all the scanned items are stuck at Phase 1.

![image](https://github.com/pentagridsec/PentagridScanController/assets/30274508/c39b88d6-b81c-4290-86d0-50271098a7bb)

This effectively means stored and second order payloads will not be tested.  Is this just me or is this a limitation due to the use of the extension driven passive audit e.g. the audit doesn't know when to move to next stages as its waiting for more inputs. 

thanks

**Comment by floyd-fuh** [comment]
Hi @AkikoOrenji I see exactly what you mean and I have experienced this before as well. I've opened a request at Portswigger. However, in the end this has absolutely nothing to do with the extension. The extension is just sending requests to the scanner and it is the scanner that then decides to stop at one point. I'll close this here (it's not an extension issue) but I'll reply here again once I get some details.

**Comment by floyd-fuh** [comment]
So it looks like your best bet is:

1. Delete old tasks that you don't need anymore
2. Restart Burp with the project
3. Use less threads

There is basically no way for you to know how thread pools map to number of browsers, which tasks get which browser instances or if a task is greedy and creates stuck browsers.

**Comment by AkikoOrenji** [comment]
Thanks for confirming not just my issue and not an issue with the extension.
